-- =====================================================================
-- Git Second Brain – Oracle AI Database 26ai schema
--
-- All objects live under the GITHUB_SECOND_BRAIN schema.
--
-- Connect as a user with privileges on GITHUB_SECOND_BRAIN, for example:
--   sqlplus system/Welcome_123@//localhost:1521/FREEPDB1 @02_create_schema.sql
-- Or connect directly as GITHUB_SECOND_BRAIN if you have the password.
-- =====================================================================

ALTER SESSION SET CURRENT_SCHEMA = GITHUB_SECOND_BRAIN;

-- Drop old objects if this script is rerun
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE GITHUB_SECOND_BRAIN.FASTAPI_COMMITS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- =====================================================================
-- Main table: one row per commit, with a 384-dim vector column
-- =====================================================================
CREATE TABLE GITHUB_SECOND_BRAIN.FASTAPI_COMMITS (
  id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sha                   VARCHAR2(64) UNIQUE NOT NULL,
  author                VARCHAR2(200),
  commit_date           TIMESTAMP,
  subject               VARCHAR2(1000),
  body                  CLOB,
  files_changed         CLOB,
  content_for_embedding CLOB,
  embedding             VECTOR(384, FLOAT32)
);

-- Supporting indexes for metadata filters (date range, author)
CREATE INDEX GITHUB_SECOND_BRAIN.FASTAPI_COMMITS_DATE_IDX
  ON GITHUB_SECOND_BRAIN.FASTAPI_COMMITS(commit_date);

CREATE INDEX GITHUB_SECOND_BRAIN.FASTAPI_COMMITS_AUTHOR_IDX
  ON GITHUB_SECOND_BRAIN.FASTAPI_COMMITS(author);

COMMIT;

-- =====================================================================
-- Vector index
-- Create AFTER loading the data (faster build, better quality).
-- Run the block below once load_data.py finishes.
-- =====================================================================
--
-- CREATE VECTOR INDEX GITHUB_SECOND_BRAIN.FASTAPI_COMMITS_VEC_IDX
-- ON GITHUB_SECOND_BRAIN.FASTAPI_COMMITS (embedding)
-- ORGANIZATION INMEMORY NEIGHBOR GRAPH
-- DISTANCE COSINE
-- WITH TARGET ACCURACY 95;
--
-- =====================================================================
