-- Core conversation/memory/telemetry tables for enterprise-ready context retention
-- Adjust tablespaces, quotas, and grants per your environment.

CREATE TABLE conversations (
  conversation_id    VARCHAR2(64) PRIMARY KEY,
  tenant_id          VARCHAR2(64) NOT NULL,
  user_id            VARCHAR2(128),
  created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  status             VARCHAR2(32)
);

CREATE TABLE messages (
  message_id         VARCHAR2(64) PRIMARY KEY,
  conversation_id    VARCHAR2(64) NOT NULL,
  role               VARCHAR2(16) CHECK (role IN ('user','assistant','system')),
  content            CLOB,
  tokens_in          NUMBER,
  tokens_out         NUMBER,
  created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_messages_conversation
    FOREIGN KEY (conversation_id) REFERENCES conversations(conversation_id)
);

CREATE INDEX idx_messages_conv_created ON messages(conversation_id, created_at);

-- Rolling long-term memory per conversation
CREATE TABLE memory_long (
  conversation_id    VARCHAR2(64) PRIMARY KEY,
  summary_text       CLOB,
  updated_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_memory_long_conversation
    FOREIGN KEY (conversation_id) REFERENCES conversations(conversation_id)
);

-- Key/value memory per conversation (for tool states, user prefs, etc.)
CREATE TABLE memory_kv (
  conversation_id    VARCHAR2(64) NOT NULL,
  key                VARCHAR2(128) NOT NULL,
  value_json         JSON,
  ttl_ts             TIMESTAMP,
  CONSTRAINT pk_memory_kv PRIMARY KEY (conversation_id, key),
  CONSTRAINT fk_memory_kv_conversation
    FOREIGN KEY (conversation_id) REFERENCES conversations(conversation_id)
);

-- Telemetry/audit of interactions
CREATE TABLE interactions (
  id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id          VARCHAR2(64),
  route              VARCHAR2(64),
  model_id           VARCHAR2(255),
  params_json        JSON,
  latency_ms         NUMBER,
  tokens_in          NUMBER,
  tokens_out         NUMBER,
  cost_est           NUMBER,
  created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_interactions_tenant_time ON interactions(tenant_id, created_at);
