-- Knowledge Base (RAG) schema: documents, chunks, embeddings, and vector index
-- Adjust VECTOR(...) DDL to match your DB 23ai version and embedding dimension.

CREATE TABLE kb_documents (
  doc_id        VARCHAR2(128) PRIMARY KEY,
  tenant_id     VARCHAR2(64) NOT NULL,
  title         VARCHAR2(256),
  uri           VARCHAR2(1024),         -- source URI (e.g., oci://bucket/prefix/file.pdf)
  mime          VARCHAR2(128),
  version       VARCHAR2(64),
  tags_json     JSON,
  hash          VARCHAR2(128),          -- content hash for idempotent ingestion
  active        NUMBER(1) DEFAULT 1,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_kb_docs_tenant_active ON kb_documents(tenant_id, active);

CREATE TABLE kb_chunks (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id       VARCHAR2(128) NOT NULL,
  tenant_id    VARCHAR2(64) NOT NULL,
  chunk_ix     NUMBER NOT NULL,
  text         CLOB,
  source_meta  JSON,
  CONSTRAINT fk_kb_chunks_doc
    FOREIGN KEY (doc_id) REFERENCES kb_documents(doc_id)
);

CREATE INDEX idx_kb_chunks_doc_ix ON kb_chunks(doc_id, chunk_ix);
CREATE INDEX idx_kb_chunks_tenant_doc ON kb_chunks(tenant_id, doc_id);

-- Embeddings table; DIMENSION must match the embedding model used (e.g., 1024 for cohere.embed-english-3)
-- Use FLOAT32 for compactness; adjust if your DB version requires different syntax.
CREATE TABLE kb_embeddings (
  chunk_id     NUMBER PRIMARY KEY,
  embedding    VECTOR(1024, FLOAT32), -- adjust 1024 to your embedding dimension
  CONSTRAINT fk_kb_embeddings_chunk
    FOREIGN KEY (chunk_id) REFERENCES kb_chunks(id)
);

-- Create a vector index for ANN search. Replace the USING clause/parameters with your DB 23ai syntax if required.
CREATE VECTOR INDEX kb_vec_idx ON kb_embeddings(embedding);

-- Helpful view joining chunks and docs
CREATE OR REPLACE VIEW kb_chunks_with_docs AS
SELECT c.id AS chunk_id,
       c.doc_id,
       d.title,
       d.uri,
       d.tags_json,
       c.tenant_id,
       c.chunk_ix,
       c.text,
       c.source_meta
  FROM kb_chunks c
  JOIN kb_documents d ON d.doc_id = c.doc_id;
